/**
 * Tests for dsh-probstat. All numeric anchors are generated by the independent
 * Python oracle test/oracle/anchors.py (math.erf / math.comb exact primitives +
 * bisection + independent t and Wilson implementations) and cross-validated
 * against published z-table and t-table values.
 *
 * ORACLE: test/oracle/anchors.py
 *
 * Discipline: every result object is checked with assertNoUndefined (lossless
 * JSON gate), and argument helpers only assign keys that are present.
 *
 * @module dsh-probstat/test
 */

import { describe, expect, it } from 'vitest'
import { buildProbstatTools } from '../src/tools.ts'
import { normalCdf, normalQuantile, tQuantile } from '../src/math.ts'

/* ------------------------------------------------------------------ */
/* helpers                                                             */
/* ------------------------------------------------------------------ */

/** Recursive lossless-JSON discipline check: no key may hold undefined. */
function assertNoUndefined(value: unknown, path = 'root'): void {
  if (value === undefined) {
    throw new Error(`undefined live key at ${path}`)
  }
  if (Array.isArray(value)) {
    value.forEach((item, index) => assertNoUndefined(item, `${path}[${index}]`))
  } else if (value !== null && typeof value === 'object') {
    for (const [key, item] of Object.entries(value as Record<string, unknown>)) {
      assertNoUndefined(item, `${path}.${key}`)
    }
  }
}

/** Build args with only defined keys (args-side lossless JSON discipline). */
function pick(entries: Record<string, unknown>): Record<string, unknown> {
  const result: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(entries)) {
    if (value !== undefined) result[key] = value
  }
  return result
}

const tools = buildProbstatTools()
const executeDist = tools.dist_calc.execute as (args: Record<string, unknown>) => Promise<Record<string, unknown>>
const executeZ = tools.z_score.execute as (args: Record<string, unknown>) => Promise<Record<string, unknown>>
const executeCi = tools.confidence_interval.execute as (args: Record<string, unknown>) => Promise<Record<string, unknown>>
const executeEvent = tools.event_probability.execute as (args: Record<string, unknown>) => Promise<Record<string, unknown>>
const executeTest = tools.hypothesis_test.execute as (args: Record<string, unknown>) => Promise<Record<string, unknown>>
const executeSample = tools.sample_size.execute as (args: Record<string, unknown>) => Promise<Record<string, unknown>>
const renderTest = tools.hypothesis_test.output.render as (args: unknown, value: unknown) => Array<{ type: string; text: string }>
const renderSample = tools.sample_size.output.render as (args: unknown, value: unknown) => Array<{ type: string; text: string }>

/* ------------------------------------------------------------------ */
/* math primitives — oracle anchors                                     */
/* ------------------------------------------------------------------ */

describe('normal distribution', () => {
  it('cdf matches the independent oracle (published z-table values)', () => {
    expect(normalCdf(1.96, 0, 1)).toBeCloseTo(0.9750021, 6)
    expect(normalCdf(2.576, 0, 1)).toBeCloseTo(0.9950025, 6)
    expect(normalCdf(0, 0, 1)).toBeCloseTo(0.5, 12)
    expect(normalCdf(-1, 0, 1)).toBeCloseTo(0.1586553, 6)
    expect(normalCdf(5, 2, 3)).toBeCloseTo(normalCdf(1, 0, 1), 6) // standardize
  })

  it('quantile matches the independent oracle (published z-table values)', () => {
    expect(normalQuantile(0.975, 0, 1)).toBeCloseTo(1.959964, 6)
    expect(normalQuantile(0.95, 0, 1)).toBeCloseTo(1.6448536, 7)
    expect(normalQuantile(0.025, 0, 1)).toBeCloseTo(-1.959964, 6)
    expect(normalQuantile(0.995, 0, 1)).toBeCloseTo(2.5758293, 7)
    expect(normalQuantile(0.5, 0, 1)).toBeCloseTo(0, 9)
  })

  it('quantile inverts cdf across the range', () => {
    for (const p of [0.001, 0.01, 0.05, 0.1, 0.3, 0.5, 0.7, 0.9, 0.95, 0.99, 0.999]) {
      const z = normalQuantile(p, 0, 1)
      expect(normalCdf(z, 0, 1)).toBeCloseTo(p, 5)
    }
  })
})

describe('binomial distribution', () => {
  it('matches the independent oracle (exact summation via math.comb)', async () => {
    let r = await executeDist(pick({ distribution: 'binomial', operation: 'pdf', n: 10, p: 0.5, x: 3 }))
    expect(r.result).toBeCloseTo(0.1171875, 12)
    r = await executeDist(pick({ distribution: 'binomial', operation: 'cdf', n: 10, p: 0.5, x: 3 }))
    expect(r.result).toBeCloseTo(0.171875, 12)
    r = await executeDist(pick({ distribution: 'binomial', operation: 'cdf', n: 20, p: 0.3, x: 5 }))
    expect(r.result).toBeCloseTo(0.4163708, 7)
    r = await executeDist(pick({ distribution: 'binomial', operation: 'survival', n: 5, p: 0.2, x: 1 }))
    expect(r.result).toBeCloseTo(0.26272, 6)
  })

  it('quantile matches the independent oracle', async () => {
    let r = await executeDist(pick({ distribution: 'binomial', operation: 'quantile', n: 10, p: 0.5, q: 0.5 }))
    expect(r.result).toBe(5)
    r = await executeDist(pick({ distribution: 'binomial', operation: 'quantile', n: 20, p: 0.4, q: 0.95 }))
    expect(r.result).toBe(12)
  })

  it('stats are closed-form np / np(1-p)', async () => {
    const r = await executeDist(pick({ distribution: 'binomial', operation: 'stats', n: 20, p: 0.4 }))
    expect(r.mean).toBeCloseTo(8, 12)
    expect(r.variance).toBeCloseTo(4.8, 12)
    expect(r.sd).toBeCloseTo(2.1908902, 7)
  })

  it('edge cases: p=0 and p=1', async () => {
    let r = await executeDist(pick({ distribution: 'binomial', operation: 'cdf', n: 5, p: 0, x: 0 }))
    expect(r.result).toBe(1)
    r = await executeDist(pick({ distribution: 'binomial', operation: 'pdf', n: 5, p: 0, x: 0 }))
    expect(r.result).toBe(1)
    r = await executeDist(pick({ distribution: 'binomial', operation: 'pdf', n: 5, p: 1, x: 5 }))
    expect(r.result).toBe(1)
    r = await executeDist(pick({ distribution: 'binomial', operation: 'cdf', n: 5, p: 1, x: 4 }))
    expect(r.result).toBe(0)
  })
})

describe('poisson distribution', () => {
  it('matches the independent oracle', async () => {
    let r = await executeDist(pick({ distribution: 'poisson', operation: 'pdf', lambda: 3, x: 2 }))
    expect(r.result).toBeCloseTo(0.2240418, 7)
    r = await executeDist(pick({ distribution: 'poisson', operation: 'cdf', lambda: 3, x: 2 }))
    expect(r.result).toBeCloseTo(0.4231901, 7)
    r = await executeDist(pick({ distribution: 'poisson', operation: 'cdf', lambda: 4.5, x: 5 }))
    expect(r.result).toBeCloseTo(0.7029304, 7)
    r = await executeDist(pick({ distribution: 'poisson', operation: 'survival', lambda: 2, x: 3 }))
    expect(r.result).toBeCloseTo(0.1428765, 7)
  })

  it('quantile matches the independent oracle', async () => {
    let r = await executeDist(pick({ distribution: 'poisson', operation: 'quantile', lambda: 3, q: 0.5 }))
    expect(r.result).toBe(3)
    r = await executeDist(pick({ distribution: 'poisson', operation: 'quantile', lambda: 10, q: 0.99 }))
    expect(r.result).toBe(18)
  })

  it('stats: mean = variance = lambda', async () => {
    const r = await executeDist(pick({ distribution: 'poisson', operation: 'stats', lambda: 4.5 }))
    expect(r.mean).toBeCloseTo(4.5, 12)
    expect(r.variance).toBeCloseTo(4.5, 12)
    expect(r.sd).toBeCloseTo(2.1213203, 7)
  })
})

describe('exponential distribution', () => {
  it('matches the independent oracle', async () => {
    let r = await executeDist(pick({ distribution: 'exponential', operation: 'pdf', lambda: 0.5, x: 1 }))
    expect(r.result).toBeCloseTo(0.3032653, 7)
    r = await executeDist(pick({ distribution: 'exponential', operation: 'cdf', lambda: 0.5, x: 1 }))
    expect(r.result).toBeCloseTo(0.3934693, 7)
    r = await executeDist(pick({ distribution: 'exponential', operation: 'survival', lambda: 0.5, x: 2 }))
    expect(r.result).toBeCloseTo(0.3678794, 7)
    r = await executeDist(pick({ distribution: 'exponential', operation: 'quantile', lambda: 0.5, q: 0.5 }))
    expect(r.result).toBeCloseTo(1.3862944, 7)
  })

  it('x < 0 gives zero density / zero cdf / unit survival with a note', async () => {
    const r = await executeDist(pick({ distribution: 'exponential', operation: 'cdf', lambda: 1, x: -1 }))
    expect(r.result).toBe(0)
    expect(r.note).toBeDefined()
  })
})

describe('uniform distribution', () => {
  it('matches the independent oracle', async () => {
    let r = await executeDist(pick({ distribution: 'uniform', operation: 'pdf', a: 0, b: 3, x: 1.5 }))
    expect(r.result).toBeCloseTo(0.3333333, 7)
    r = await executeDist(pick({ distribution: 'uniform', operation: 'cdf', a: 0, b: 3, x: 2 }))
    expect(r.result).toBeCloseTo(0.6666667, 7)
    r = await executeDist(pick({ distribution: 'uniform', operation: 'cdf', a: 0, b: 3, x: -1 }))
    expect(r.result).toBe(0)
    r = await executeDist(pick({ distribution: 'uniform', operation: 'quantile', a: 2, b: 6, q: 0.25 }))
    expect(r.result).toBe(3)
  })

  it('stats: mean (a+b)/2, variance (b-a)^2/12', async () => {
    const r = await executeDist(pick({ distribution: 'uniform', operation: 'stats', a: 2, b: 6 }))
    expect(r.mean).toBe(4)
    expect(r.variance).toBeCloseTo(1.3333333, 7)
  })
})

describe('geometric distribution (failures before first success)', () => {
  it('matches the independent oracle', async () => {
    let r = await executeDist(pick({ distribution: 'geometric', operation: 'pdf', p: 0.3, x: 2 }))
    expect(r.result).toBeCloseTo(0.147, 9)
    r = await executeDist(pick({ distribution: 'geometric', operation: 'cdf', p: 0.3, x: 2 }))
    expect(r.result).toBeCloseTo(0.657, 9)
    r = await executeDist(pick({ distribution: 'geometric', operation: 'survival', p: 0.25, x: 1 }))
    expect(r.result).toBeCloseTo(0.5625, 9)
    r = await executeDist(pick({ distribution: 'geometric', operation: 'quantile', p: 0.5, q: 0.5 }))
    expect(r.result).toBe(0)
    expect(r.note).toBeDefined()
  })

  it('stats: mean (1-p)/p, variance (1-p)/p^2', async () => {
    const r = await executeDist(pick({ distribution: 'geometric', operation: 'stats', p: 0.25 }))
    expect(r.mean).toBe(3)
    expect(r.variance).toBe(12)
  })
})

/* ------------------------------------------------------------------ */
/* z_score                                                             */
/* ------------------------------------------------------------------ */

describe('z_score tool', () => {
  it('to_prob matches the independent oracle', async () => {
    const r = await executeZ(pick({ mode: 'to_prob', z: 1.96 }))
    expect(r.probability).toBeCloseTo(0.9750021, 6)
    expect(r.percentile).toBeCloseTo(97.50021, 4)
    expect(r.percentile).toBeCloseTo((r.probability as number) * 100, 9)
  })

  it('from_prob matches the independent oracle', async () => {
    const r = await executeZ(pick({ mode: 'from_prob', p: 0.975 }))
    expect(r.z).toBeCloseTo(1.959964, 6)
    expect(r.percentile).toBeCloseTo(97.5, 6)
  })

  it('two_sided matches the independent oracle', async () => {
    let r = await executeZ(pick({ mode: 'two_sided', z: 1.96 }))
    expect(r.pValue).toBeCloseTo(0.0499958, 6)
    r = await executeZ(pick({ mode: 'two_sided', z: 2 }))
    expect(r.pValue).toBeCloseTo(0.0455003, 6)
  })

  it('between matches the independent oracle and sorts the bounds', async () => {
    const r = await executeZ(pick({ mode: 'between', z1: -1, z2: 1 }))
    expect(r.probability).toBeCloseTo(0.6826895, 6)
    const swapped = await executeZ(pick({ mode: 'between', z1: 1, z2: -1 }))
    expect(swapped.probability).toBeCloseTo(0.6826895, 6)
    expect(swapped.z1).toBe(-1)
    expect(swapped.z2).toBe(1)
  })

  it('rejects out-of-range p', async () => {
    const r = await executeZ(pick({ mode: 'from_prob', p: 1 }))
    expect(r.valid).toBe(false)
    expect(r.error).toBeDefined()
  })
})

/* ------------------------------------------------------------------ */
/* confidence_interval                                                 */
/* ------------------------------------------------------------------ */

describe('confidence_interval tool', () => {
  it('mean_z matches the independent oracle', async () => {
    const r = await executeCi(pick({ kind: 'mean_z', mean: 100, sigma: 15, n: 30 }))
    expect(r.lower).toBeCloseTo(94.6324176, 7)
    expect(r.upper).toBeCloseTo(105.3675824, 7)
    expect(r.marginOfError).toBeCloseTo(5.3675824, 7)
    expect(r.criticalValue).toBeCloseTo(1.959964, 6)
    expect(r.standardError).toBeCloseTo(2.7386128, 7)
  })

  it('mean_t matches the independent oracle (published t-table: 2.201 at df=11)', async () => {
    const r = await executeCi(pick({ kind: 'mean_t', mean: 5, sd: 1.5, n: 12 }))
    expect(r.lower).toBeCloseTo(4.0469455, 7)
    expect(r.upper).toBeCloseTo(5.9530545, 7)
    expect(r.marginOfError).toBeCloseTo(0.9530545, 7)
    expect(r.criticalValue).toBeCloseTo(2.2009852, 6)
  })

  it('proportion matches the independent oracle (Wilson interval)', async () => {
    let r = await executeCi(pick({ kind: 'proportion', successes: 40, n: 100 }))
    expect(r.lower).toBeCloseTo(0.3094013, 7)
    expect(r.upper).toBeCloseTo(0.4979974, 7)
    r = await executeCi(pick({ kind: 'proportion', successes: 0, n: 50 }))
    expect(r.lower).toBeCloseTo(0, 9)
    expect(r.upper).toBeCloseTo(0.0713476, 7)
    r = await executeCi(pick({ kind: 'proportion', successes: 50, n: 50 }))
    expect(r.lower).toBeCloseTo(0.9286524, 7)
    expect(r.upper).toBeCloseTo(1, 9)
  })

  it('rejects bad inputs with a clear error', async () => {
    let r = await executeCi(pick({ kind: 'mean_t', mean: 5, sd: 1.5, n: 1 }))
    expect(r.valid).toBe(false)
    r = await executeCi(pick({ kind: 'proportion', successes: 7, n: 5 }))
    expect(r.valid).toBe(false)
  })
})

/* ------------------------------------------------------------------ */
/* event_probability                                                   */
/* ------------------------------------------------------------------ */

describe('event_probability tool', () => {
  it('union (independent and mutually exclusive)', async () => {
    let r = await executeEvent(pick({ operation: 'union', pA: 0.3, pB: 0.4 }))
    expect(r.result).toBeCloseTo(0.58, 9)
    expect(r.formula).toBeDefined()
    r = await executeEvent(pick({ operation: 'union', pA: 0.3, pB: 0.4, independent: false }))
    expect(r.result).toBeCloseTo(0.7, 9)
  })

  it('intersection (independent)', async () => {
    const r = await executeEvent(pick({ operation: 'intersection', pA: 0.3, pB: 0.4 }))
    expect(r.result).toBeCloseTo(0.12, 9)
  })

  it('intersection without independence is refused', async () => {
    const r = await executeEvent(pick({ operation: 'intersection', pA: 0.3, pB: 0.4, independent: false }))
    expect(r.valid).toBe(false)
  })

  it('conditional', async () => {
    const r = await executeEvent(pick({ operation: 'conditional', pIntersection: 0.2, pCondition: 0.5 }))
    expect(r.result).toBeCloseTo(0.4, 9)
  })

  it('bayes matches the independent oracle (classic medical test example)', async () => {
    const r = await executeEvent(pick({ operation: 'bayes', prior: 0.01, truePositive: 0.99, falsePositive: 0.05 }))
    expect(r.result).toBeCloseTo(0.1666667, 7)
  })

  it('complement and at_least_one', async () => {
    let r = await executeEvent(pick({ operation: 'complement', p: 0.25 }))
    expect(r.result).toBeCloseTo(0.75, 9)
    r = await executeEvent(pick({ operation: 'at_least_one', p: 0.1, n: 5 }))
    expect(r.result).toBeCloseTo(0.40951, 6)
  })

  it('rejects invalid probabilities', async () => {
    let r = await executeEvent(pick({ operation: 'complement', p: 1.5 }))
    expect(r.valid).toBe(false)
    r = await executeEvent(pick({ operation: 'bayes', prior: 1, truePositive: 0, falsePositive: 0 }))
    expect(r.valid).toBe(false)
  })
})

/* ------------------------------------------------------------------ */
/* hypothesis_test                                                     */
/* ------------------------------------------------------------------ */

describe('hypothesis_test tool', () => {
  it('mean_z (known sigma) matches the independent oracle', async () => {
    const r = await executeTest(pick({ kind: 'mean_z', sampleMean: 102, mu0: 100, sigma: 15, n: 36 }))
    expect(r.statistic).toBeCloseTo(0.8, 12)
    expect(r.standardError).toBeCloseTo(2.5, 12)
    expect(r.pValue).toBeCloseTo(0.4237108, 6)
    expect(r.pValueTwoSided).toBeCloseTo(0.4237108, 6)
    expect(r.pValueLeft).toBeCloseTo(0.7881446, 6)
    expect(r.pValueRight).toBeCloseTo(0.2118554, 6)
    expect(r.criticalValue).toBeCloseTo(1.959964, 6)
    expect(r.alpha).toBe(0.05)
    expect(r.reject).toBe(false)
    expect(r.df).toBeUndefined()
  })

  it('mean_z honours the requested tail and the critical value follows it', async () => {
    const r = await executeTest(pick({ kind: 'mean_z', sampleMean: 102, mu0: 100, sigma: 15, n: 36, tail: 'right' }))
    expect(r.pValue).toBeCloseTo(0.2118554, 6)
    expect(r.criticalValue).toBeCloseTo(1.6448536, 6)

    const l = await executeTest(pick({ kind: 'mean_z', sampleMean: 100, mu0: 103, sigma: 10, n: 25, tail: 'left' }))
    expect(l.statistic).toBeCloseTo(-1.5, 12)
    expect(l.pValue).toBeCloseTo(0.0668072, 6)
    expect(l.criticalValue).toBeCloseTo(-1.6448536, 6)
    expect(l.reject).toBe(false)
  })

  it('mean_t uses df = n - 1 and Student-t p-values (oracle)', async () => {
    const r = await executeTest(pick({ kind: 'mean_t', sampleMean: 5.2, mu0: 5, sd: 1.5, n: 12, tail: 'right' }))
    expect(r.statistic).toBeCloseTo(0.4618802, 7)
    expect(r.standardError).toBeCloseTo(0.4330127, 7)
    expect(r.df).toBe(11)
    expect(r.pValue).toBeCloseTo(0.3265839, 6)
    expect(r.pValueTwoSided).toBeCloseTo(0.6531677, 6)
    expect(r.criticalValue).toBeCloseTo(1.7958848, 6)

    const two = await executeTest(pick({ kind: 'mean_t', sampleMean: 5.2, mu0: 5, sd: 1.5, n: 12 }))
    expect(two.criticalValue).toBeCloseTo(2.2009852, 6)
  })

  it('proportion uses p0 in the standard error and rejects at alpha = 0.05', async () => {
    const r = await executeTest(pick({ kind: 'proportion', successes: 40, n: 100, p0: 0.5 }))
    expect(r.statistic).toBeCloseTo(-2, 12)
    expect(r.standardError).toBeCloseTo(0.05, 12)
    expect(r.pValue).toBeCloseTo(0.0455003, 6)
    expect(r.pValueLeft).toBeCloseTo(0.0227501, 6)
    expect(r.criticalValue).toBeCloseTo(1.959964, 6)
    expect(r.reject).toBe(true)

    const hi = await executeTest(pick({ kind: 'proportion', successes: 62, n: 100, p0: 0.5, tail: 'right' }))
    expect(hi.statistic).toBeCloseTo(2.4, 12)
    expect(hi.pValue).toBeCloseTo(0.0081975, 6)
  })

  it('flags an unreliable normal approximation instead of hiding it', async () => {
    const r = await executeTest(pick({ kind: 'proportion', successes: 1, n: 10, p0: 0.1 }))
    expect(r.valid).toBe(true)
    expect(String(r.note)).toContain('normal approximation')
    expect(String(r.note)).toContain('n*p0 = 1')

    const solid = await executeTest(pick({ kind: 'proportion', successes: 40, n: 100, p0: 0.5 }))
    expect(solid.note).toBeUndefined()
  })

  it('rejects bad inputs with a clear error', async () => {
    let r = await executeTest(pick({ kind: 'mean_z', sampleMean: 1, sigma: 1, n: 4 }))
    expect(r.valid).toBe(false)
    r = await executeTest(pick({ kind: 'mean_z', sampleMean: 1, mu0: 0, sigma: 0, n: 4 }))
    expect(r.valid).toBe(false)
    r = await executeTest(pick({ kind: 'mean_t', sampleMean: 1, mu0: 0, sd: 1, n: 1 }))
    expect(r.valid).toBe(false)
    r = await executeTest(pick({ kind: 'proportion', successes: 7, n: 5, p0: 0.5 }))
    expect(r.valid).toBe(false)
    r = await executeTest(pick({ kind: 'proportion', successes: 2, n: 10, p0: 0 }))
    expect(r.valid).toBe(false)
    r = await executeTest(pick({ kind: 'mean_z', sampleMean: 1, mu0: 0, sigma: 1, n: 4, alpha: 0 }))
    expect(r.valid).toBe(false)
  })

  it('renders the decision in the tool text', async () => {
    const value = await executeTest(pick({ kind: 'proportion', successes: 40, n: 100, p0: 0.5 }))
    const [block] = renderTest({}, value)
    expect(block.type).toBe('text')
    expect(block.text).toContain('reject the null hypothesis')
    expect(block.text).toContain('critical value')

    const failed = renderTest({}, { valid: false, error: 'boom' })
    expect(failed[0].text).toContain('boom')
  })
})

/* ------------------------------------------------------------------ */
/* sample_size                                                         */
/* ------------------------------------------------------------------ */

describe('sample_size tool', () => {
  it('mean_z matches the independent oracle (with the ceiling applied)', async () => {
    const r = await executeSample(pick({ kind: 'mean_z', sigma: 15, marginOfError: 5 }))
    expect(r.criticalValue).toBeCloseTo(1.959964, 6)
    expect(r.nExact).toBeCloseTo(34.573129, 6)
    expect(r.n).toBe(35)
    expect(r.conf).toBe(0.95)

    const tight = await executeSample(pick({ kind: 'mean_z', sigma: 15, marginOfError: 5, conf: 0.99 }))
    expect(tight.criticalValue).toBeCloseTo(2.5758293, 6)
    expect(tight.nExact).toBeCloseTo(59.71407, 5)
    expect(tight.n).toBe(60)
  })

  it('proportion with the Wald closed form (explicit and default p)', async () => {
    const r = await executeSample(pick({ kind: 'proportion', p: 0.5, marginOfError: 0.03 }))
    expect(r.method).toBe('wald')
    expect(r.nExact).toBeCloseTo(1067.0719, 4)
    expect(r.n).toBe(1068)
    expect(r.assumedP).toBe(0.5)

    const q = await executeSample(pick({ kind: 'proportion', p: 0.2, marginOfError: 0.05 }))
    expect(q.nExact).toBeCloseTo(245.8534, 4)
    expect(q.n).toBe(246)

    const dflt = await executeSample(pick({ kind: 'proportion', marginOfError: 0.03 }))
    expect(dflt.assumedP).toBe(0.5)
    expect(String(dflt.note)).toContain('worst case')
  })

  it('proportion with the Wilson method returns the smallest n meeting the target', async () => {
    const r = await executeSample(pick({ kind: 'proportion', p: 0.5, marginOfError: 0.03, method: 'wilson' }))
    expect(r.method).toBe('wilson')
    expect(r.n).toBe(1064)
    expect(String(r.note)).toContain('Wilson')

    const q = await executeSample(pick({ kind: 'proportion', p: 0.2, marginOfError: 0.05, method: 'wilson' }))
    expect(q.n).toBe(245)
  })

  it('rejects impossible targets and bad inputs', async () => {
    let r = await executeSample(pick({ kind: 'proportion', p: 0.5, marginOfError: 0, method: 'wilson' }))
    expect(r.valid).toBe(false)
    r = await executeSample(pick({ kind: 'proportion', p: 0.5, marginOfError: 1e-6, method: 'wilson' }))
    expect(r.valid).toBe(false)
    expect(String(r.error)).toContain('no sample size up to')
    r = await executeSample(pick({ kind: 'mean_z', sigma: 0, marginOfError: 5 }))
    expect(r.valid).toBe(false)
    r = await executeSample(pick({ kind: 'proportion', p: 1, marginOfError: 0.03 }))
    expect(r.valid).toBe(false)
    r = await executeSample(pick({ kind: 'proportion', p: 0.5, marginOfError: 0.03, conf: 1 }))
    expect(r.valid).toBe(false)
  })

  it('renders the required n in the tool text', async () => {
    const value = await executeSample(pick({ kind: 'mean_z', sigma: 15, marginOfError: 5 }))
    const [block] = renderSample({}, value)
    expect(block.text).toContain('required n: 35')
    expect(block.text).toContain('critical value')

    const failed = renderSample({}, { valid: false, error: 'boom' })
    expect(failed[0].text).toContain('boom')
  })
})

/* ------------------------------------------------------------------ */
/* discipline: lossless JSON + validation                              */
/* ------------------------------------------------------------------ */

describe('discipline checks', () => {
  it('every result tree is free of undefined live keys', async () => {
    const cases: Promise<Record<string, unknown>>[] = [
      executeDist(pick({ distribution: 'normal', operation: 'cdf', x: 1.5 })),
      executeDist(pick({ distribution: 'normal', operation: 'stats' })),
      executeDist(pick({ distribution: 'binomial', operation: 'quantile', n: 10, p: 0.5, q: 0.5 })),
      executeDist(pick({ distribution: 'exponential', operation: 'cdf', lambda: 1, x: -1 })),
      executeDist(pick({ distribution: 'geometric', operation: 'cdf', p: 0.3, x: 2 })),
      executeDist(pick({ distribution: 'normal', operation: 'cdf' })),
      executeZ(pick({ mode: 'between', z1: -1, z2: 1 })),
      executeCi(pick({ kind: 'mean_z', mean: 100, sigma: 15, n: 30 })),
      executeCi(pick({ kind: 'proportion', successes: 40, n: 100 })),
      executeEvent(pick({ operation: 'bayes', prior: 0.01, truePositive: 0.99, falsePositive: 0.05 })),
      executeTest(pick({ kind: 'mean_z', sampleMean: 102, mu0: 100, sigma: 15, n: 36 })),
      executeTest(pick({ kind: 'mean_t', sampleMean: 5.2, mu0: 5, sd: 1.5, n: 12 })),
      executeTest(pick({ kind: 'proportion', successes: 1, n: 10, p0: 0.1 })),
      executeTest(pick({ kind: 'mean_z', sampleMean: 1, sigma: 1, n: 4 })),
      executeSample(pick({ kind: 'mean_z', sigma: 15, marginOfError: 5 })),
      executeSample(pick({ kind: 'proportion', marginOfError: 0.03 })),
      executeSample(pick({ kind: 'proportion', p: 0.5, marginOfError: 0.03, method: 'wilson' })),
      executeSample(pick({ kind: 'proportion', p: 0.5, marginOfError: 1e-6, method: 'wilson' })),
    ]
    for (const result of await Promise.all(cases)) {
      assertNoUndefined(result)
    }
  })

  it('invalid enum values are rejected at the schema layer', async () => {
    await expect(executeDist(pick({ distribution: 'bogus', operation: 'cdf', x: 1 }))).rejects.toThrow()
    await expect(executeDist(pick({ distribution: 'normal', operation: 'bogus', x: 1 }))).rejects.toThrow()
    await expect(executeZ(pick({ mode: 'bogus' }))).rejects.toThrow()
    await expect(executeCi(pick({ kind: 'bogus' }))).rejects.toThrow()
    await expect(executeEvent(pick({ operation: 'bogus' }))).rejects.toThrow()
    await expect(executeTest(pick({ kind: 'anova' }))).rejects.toThrow()
    await expect(executeTest(pick({ kind: 'mean_z', sampleMean: 1, mu0: 0, sigma: 1, n: 4, tail: 'both' }))).rejects.toThrow()
    await expect(executeSample(pick({ kind: 'median', marginOfError: 0.03 }))).rejects.toThrow()
    await expect(executeSample(pick({ kind: 'proportion', p: 0.5, marginOfError: 0.03, method: 'exact' }))).rejects.toThrow()
  })

  it('missing required properties are rejected at the schema layer', async () => {
    await expect(executeSample(pick({ kind: 'mean_z', sigma: 15 }))).rejects.toThrow(/marginOfError/)
    await expect(executeSample(pick({ kind: 'mean_z' }))).rejects.toThrow(/marginOfError/)
  })

  it('validation errors carry valid=false and a message, never undefined keys', async () => {
    const r = await executeDist(pick({ distribution: 'normal', operation: 'quantile', q: 2 }))
    expect(r.valid).toBe(false)
    expect(typeof r.error).toBe('string')
    assertNoUndefined(r)
  })

  it('default operation is cdf and default normal is standard', async () => {
    const r = await executeDist(pick({ distribution: 'normal', x: 1.96 }))
    expect(r.operation).toBe('cdf')
    expect(r.result).toBeCloseTo(0.9750021, 6)
  })
})

/* ------------------------------------------------------------------ */
/* published t-table cross-checks                                      */
/* ------------------------------------------------------------------ */

describe('t-distribution published table cross-checks', () => {
  it('t-quantiles match published values', () => {
    expect(tQuantile(0.975, 10)).toBeCloseTo(2.2281, 3)
    expect(tQuantile(0.975, 29)).toBeCloseTo(2.0452, 3)
    expect(tQuantile(0.95, 10)).toBeCloseTo(1.8125, 3)
    expect(tQuantile(0.975, 100)).toBeCloseTo(1.984, 3)
  })
})
